
List<String> europeanCarMakers = [
  'Audi',
  'BMW',
  'Mercedes-Benz',
  'Volkswagen',
  'Porsche',
  'Ferrari',
  'Lamborghini',
  'Fiat',
  'Alfa Romeo',
  'Maserati',
  'Peugeot',
  'Renault',
  'Citroën',
  'Bugatti',
  'Bentley',
  'Rolls-Royce',
  'Aston Martin',
  'Jaguar',
  'Land Rover',
  'Volvo',
  'SEAT',
  'Skoda',
  'Mini',
  'Pagani',
  'Koenigsegg'
];

Map<String, List<String>> carModelsByMaker = {
  'Audi': ['A3', 'A4', 'A6', 'Q5', 'Q7', 'R8', 'TT'],
  'BMW': ['3 Series', '5 Series', '7 Series', 'X3', 'X5', 'M3', 'i8'],
  'Mercedes-Benz': ['C-Class', 'E-Class', 'S-Class', 'GLC', 'GLE', 'A-Class', 'G-Class'],
  'Volkswagen': ['Golf', 'Passat', 'Polo', 'Tiguan', 'Touareg', 'Beetle'],
  'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Boxster', 'Taycan'],
  'Ferrari': ['488', 'F8 Tributo', '812 Superfast', 'Roma', 'SF90 Stradale', 'Portofino'],
  'Lamborghini': ['Aventador', 'Huracan', 'Urus', 'Gallardo', 'Murcielago'],
  'Fiat': ['500', 'Panda', 'Tipo', 'Punto', 'Ducato'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Giulietta', '4C', '8C Competizione'],
  'Maserati': ['Ghibli', 'Levante', 'Quattroporte', 'GranTurismo', 'GranCabrio'],
  'Peugeot': ['208', '308', '3008', '5008', '508', '2008'],
  'Renault': ['Clio', 'Megane', 'Kadjar', 'Captur', 'Talisman'],
  'Citroën': ['C3', 'C4', 'C5 Aircross', 'Berlingo', 'DS3'],
  'Bugatti': ['Veyron', 'Chiron', 'Divo', 'La Voiture Noire'],
  'Bentley': ['Continental GT', 'Flying Spur', 'Bentayga', 'Mulsanne'],
  'Rolls-Royce': ['Phantom', 'Ghost', 'Wraith', 'Cullinan', 'Dawn'],
  'Aston Martin': ['DB11', 'Vantage', 'DBS', 'Rapide', 'Valkyrie'],
  'Jaguar': ['XE', 'XF', 'F-Pace', 'I-Pace', 'F-Type'],
  'Land Rover': ['Range Rover', 'Discovery', 'Defender', 'Evoque', 'Velar'],
  'Volvo': ['XC90', 'XC60', 'S60', 'V60', 'S90'],
  'SEAT': ['Ibiza', 'Leon', 'Ateca', 'Arona', 'Tarraco'],
  'Skoda': ['Octavia', 'Superb', 'Kodiaq', 'Karoq', 'Fabia'],
  'Mini': ['Cooper', 'Countryman', 'Clubman', 'Paceman'],
  'Pagani': ['Huayra', 'Zonda'],
  'Koenigsegg': ['Agera', 'Regera', 'Jesko', 'Gemera'],
};
